name: CI

on: [push]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Lint
        run: yarn typecheck
      - name: Test
        run: yarn test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Build
        run: yarn build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [validate, build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup
        run: yarn
      - name: Deploy Preview
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
